name: PortalStick
main: com.matejdro.bukkit.portalstick.PortalStick
version: 2.1.0
author: matejdro and oliverw92
commands:
  portal:
    description: Aperture Science Portal Stick
    aliases:
    usage: /<command> help