name: PortalStick
main: com.matejdro.bukkit.portalstick.PortalStick
version: 3.0.0
author: matejdro and oliverw92
depend: []
commands:
  portalstick:
    description: Aperture Science Portal Stick
    aliases: portal
    usage: /<command> help
