name: PortalStick
main: com.matejdro.bukkit.portalstick.PortalStick
version: 2.2.1
author: matejdro and oliverw92
commands:
  portalstick:
    description: Aperture Science Portal Stick
    aliases: portal
    usage: /<command> help